language: go
arch:
  - amd64
  - ppc64le
go:
  - 1.x
  - "1.20"
  - "1.21"
# Disable version go:1.21
jobs:
  exclude:
    - arch: amd64
      go: "1.21"
    - arch: ppc64le
      go: "1.21"

install: go get -t -d -v ./... && go build -v ./...
